# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_auto_20171221_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('on', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=380)),
                ('rating', models.IntegerField(default=0)),
                ('made', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('imageDir', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=40)),
                ('bakeType', models.CharField(choices=[('CAKES', 'cakes & cupcakes'), ('PIES', 'pies'), ('COOKIES', 'cookies'), ('OTHER', 'other')], default='CAKES', max_length=10)),
                ('serve', models.CharField(max_length=2)),
                ('prepTime', models.CharField(max_length=20)),
                ('cookTime', models.CharField(max_length=30)),
                ('kcal', models.CharField(default=0, max_length=10)),
                ('fat', models.CharField(default=0, max_length=10)),
                ('carbs', models.CharField(default=0, max_length=10)),
                ('sugar', models.CharField(default=0, max_length=10)),
                ('protein', models.CharField(default=0, max_length=10)),
                ('salt', models.CharField(default=0, max_length=10)),
                ('ingredients', models.TextField(max_length=9000)),
                ('recipe', models.TextField(max_length=9000)),
                ('rating', models.IntegerField(default=0)),
                ('numberOfVotes', models.IntegerField(default=0)),
                ('totalRating', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
