# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0006_auto_20171221_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='name',
        ),
    ]
