# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0007_auto_20171221_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='author',
        ),
    ]
