# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0008_auto_20171221_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
