# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0012_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rating',
            new_name='rate',
        ),
    ]
