# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 11:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0018_auto_20180113_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_favorites', to='bakery.Recipes'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_made', to='bakery.Recipes'),
        ),
    ]
