# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 21:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bakery', '0019_auto_20180113_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favs',
        ),
        migrations.AddField(
            model_name='profile',
            name='favs',
            field=models.ManyToManyField(blank=True, null=True, related_name='profile_favorites', to='bakery.Recipes'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='profile_friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='made',
        ),
        migrations.AddField(
            model_name='profile',
            name='made',
            field=models.ManyToManyField(blank=True, null=True, related_name='profile_made', to='bakery.Recipes'),
        ),
    ]
